name: Azure Pipelines
variables:
  python.version: '3.7.6'

stages:
- stage: Provision
  displayName: Provision for Azure Pipeline
  jobs:
    - job: provision_azure_infrastructure
      displayName: Provisioning AppService
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
        - task: TerraformInstaller@0
          displayName: Install Terraform

        - task: TerraformCLI@0
          displayName: 'check terraform version'
          inputs:
            command: version

        - task: DownloadSecureFile@1
          name: principal
          displayName: 'Download azure principal confidential'
          inputs:
            secureFile: 'set_azure_env.sh'
        
        - task: DownloadSecureFile@1
          name: sshkey
          displayName: 'Download SSH Public Key'
          inputs:
            secureFile: 'id_rsa.pub'
        
        - task: DownloadSecureFile@1
          name: privatekey
          displayName: 'Download SSH private Key'
          inputs:
            secureFile: 'id_rsa'

        - task: Bash@3
          displayName: "Copy SSH key"
          inputs:
            targetType: 'inline'
            script: |
              mkdir -p ~/.ssh
              cp $(sshkey.secureFilePath) ~/.ssh
              cp $(privatekey.secureFilePath) ~/.ssh
              chmod 400 ~/.ssh/id_rsa.pub
              chmod 400 ~/.ssh/id_rsa
                   
        - bash: |
            cp $(principal.secureFilePath) $(System.DefaultWorkingDirectory)/terraform
            cd $(System.DefaultWorkingDirectory)/terraform
            chmod 400 set_azure_env.sh
          displayName: Copy set_azure_env.sh
        
        - bash: |
            echo Set Terraform Environment
            cd $(System.DefaultWorkingDirectory)/terraform
            ./set_azure_env.sh
          displayName: Set Terraform Environment

        - bash: |
            echo System Default Working Directory: $(System.DefaultWorkingDirectory)
            echo Azure Principal at : $(principal.secureFilePath)
            cd $(Agent.TempDirectory)
            pwd
            ls -la
            cat id_rsa.pub
            cd ~/.ssh/
            pwd
            ls -la
            cat known_hosts
            cd $(System.DefaultWorkingDirectory)  
            pwd
            ls -la
          displayName: Check build environment
        
        - task: TerraformTaskV1@0
          displayName: Terraform Init
          inputs:
            provider: azurerm
            command:  init
            backendServiceArm: 'proj3'
            backendAzureRmResourceGroupName: 'proj3'
            backendAzureRmStorageAccountName: 'proj328212'
            backendAzureRmContainerName: 'proj3con'
            backendAzureRmKey: 'terraform.tfstate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        
        - task: TerraformTaskV1@0
          displayName: Terraform Apply
          inputs:
            provider: azurerm
            command: 'apply'
            commandOptions: |
              -auto-approve
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            environmentServiceNameAzureRM: 'proj3'



        


- stage: Build
  jobs:    
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    # Needed for Terraform VM deployment
    
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'path/to/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi


# - stage: Deployment
  # jobs:
  # - deployment: FakeRestAPI
  #   pool:
  #     vmImage: 'Ubuntu-16.04'
  #   environment: 'TEST'
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - task: AzureWebApp@1
  #           displayName: 'Deploy Azure Web App'
  #           inputs:
  #             azureSubscription: ''
  #             appName: ''
  #             appType: webApp
  #             package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
  
  
  
  # - deployment: VMDeploy
  #   displayName: NAME
  #   environment:
  #     name:  ENVIRONMENT NAME
  #     resourceType: VirtualMachine
  #     tags: TAG NAME
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               #! /bin/bash
                
  #               sudo apt-get upgrade -y
  #               sudo apt-get install python3-pip -y
  #               sudo apt-get install unzip -y
  #               sudo apt-get install -y chromium-browser
  #               pip3 install selenium
  #               export PATH=$PATH:some/path


